services:
  cc-db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=login
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 2s
      retries: 10
  cc-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes: 
      - .:/cc-backend
    ports:
      - "1337:1337"
    restart: unless-stopped
    # healthcheck: # Scratch images don't have wget or curl, need to create health-check bin
    #   test:  ["CMD", "wget", "--spider", "-q", "localhost:1337/health"]
    #   interval: 2s
    #   retries: 5
    #   start_period: 5s  
  cc-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - .:/cc-frontend
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      cc-db:
        condition: service_healthy
      # cc-backend:
      #   condition: service_healthy

volumes:
  postgres_data:
    