services:
  cc-db:
    build:
      context: .
      dockerfile: db/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - db/.env.docker
    environment:
      - DB_AND_USER=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -d $${DB_AND_USER} -U $${DB_AND_USER}
      interval: 2s
      retries: 10
    networks:
      - coolchat-network 
  cc-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes: 
      - .:/cc-backend
    ports:
      - "1337:1337"
    env_file:
      - backend/.env
      - backend/.env.docker
    restart: unless-stopped
    # healthcheck: # Scratch images don't have wget or curl, need to create health-check binary or smth
    #   test:  ["CMD", "wget", "--spider", "-q", "localhost:1337/health"]
    #   interval: 2s
    #   retries: 5
    #   start_period: 5s  
    networks:
      - coolchat-network 
    depends_on:
      cc-db:
        condition: service_healthy
  cc-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - .:/cc-frontend
    ports:
      - "8000:8000"
    env_file:
      - frontend/.env
      - frontend/.env.docker
    restart: unless-stopped
    networks:
      - coolchat-network 
    depends_on:
      cc-db:
        condition: service_healthy
      # cc-backend:
      #   condition: service_healthy

volumes:
  postgres_data:

networks:
  coolchat-network:
    driver: bridge