services:
  cc-db:
    image: postgres:latest
    volumes:
      - coolchatdb-data:/var/lib/postgresql/data/
    env_file:
      - .env.docker
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -d coolchatdb -U postgres
      interval: 2s
      retries: 10
    networks:
      - cc-network 
  cc-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes: 
      - .:/cc-backend
    ports:
      - 1337:1337
    env_file:
      - .env.docker
    restart: unless-stopped
    # healthcheck: # Scratch images don't have wget or curl, need to create health-check binary or smth
    #   test:  ["CMD", "wget", "--spider", "-q", "localhost:1337/health"]
    #   interval: 2s
    #   retries: 5
    #   start_period: 5s  
    networks:
      - cc-network 
    depends_on:
      cc-db:
        condition: service_healthy
  cc-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - .:/cc-frontend
    ports:
      - 8000:8000
    env_file:
      - .env.docker
    restart: unless-stopped
    networks:
      - cc-network 
    depends_on:
      cc-db:
        condition: service_healthy
      # remove db dependency if backend healthcheck is fixed
      # cc-backend:
      #   condition: service_healthy

volumes:
  coolchatdb-data:

networks:
  cc-network:
    driver: bridge