name: coolchat-tests
services:
  run:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./reports:/coolchat-tests/reports
    command:
      - pytest
    env_file:
      - .env.docker